"""Writes engine/PolyPitchFilters.h: the designed band-filter prototypes (filterdesign.designed, the same ones the
reference uses) for the sample rates the engine supports natively. Designing one is a 2000 to 4600 unknown
least-squares solve, far too slow for an audio plug-in's prepare call, so they are tables.

    python reference/make_filters.py
"""
import os
import numpy as np
from filterdesign import prototype, describe

RATES = (44100, 48000)
# (bands K, delay ms, tail ms). Which one is used when is in polypitch_ref.shift and the engine's makeBank:
#   512 bands,  8 ms   shifting up, fast response
#   512 bands, 12 ms   shifting down (the attack is played straight from the input, so the delay is hidden), and shifting up, balanced
#   1024 bands, 16 ms  shifting up, clean response (bands half as wide)
CONFIGS = ((512, 8.0, 40.0), (512, 12.0, 60.0), (1024, 16.0, 80.0))

out = ["// Generated by reference/make_filters.py - do not edit. Band-filter prototypes h[n], n = 0 (newest sample) .. tau + tail.",
       "// 512 bands, 8 ms delay / 40 ms tail: shifting up, fast response. 512 bands, 12 ms / 60 ms: shifting down (where the attack",
       "// bridge hides the delay) and shifting up, balanced response. 1024 bands, 16 ms / 80 ms: shifting up, clean response.",
       "// Copyright (c) 2026 Ben Juodvalkis. MIT License (see LICENSE).",
       "#pragma once", "namespace polypitch { namespace filters {", "struct Table { int sampleRate; int K; int tau; int length; const double* h; };"]
tabs = []
for sr in RATES:
    for K, tau_ms, tail_ms in CONFIGS:
        tau = int(round(tau_ms * sr / 1000)); tail = int(round(tail_ms * sr / 1000)); h = prototype(K, tau, tail); name = f"h_{sr}_{K}_{tau_ms:g}ms"
        out.append(f"static const double {name}[{len(h)}] = {{")
        for i in range(0, len(h), 6): out.append("  " + ", ".join(f"{v:.17e}" for v in h[i:i + 6]) + ",")
        out.append("};"); tabs.append(f"  {{ {sr}, {K}, {tau}, {len(h)}, {name} }},")
        print(f"{name}: {K} bands, delay {tau} samples, {len(h)} taps | {describe(h, K, tau, sr)}")
out += [f"static const Table tables[{len(tabs)}] = {{"] + tabs + ["};", f"static const int numTables = {len(tabs)};", "} }"]
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "engine", "PolyPitchFilters.h"), "w").write("\n".join(out) + "\n")
